### PR TITLE
tell user about a successfull login

### PR DESCRIPTION
**Pull request by meleu**
The official RA emulators shows a message about a successfull login. This change tries to reproduce a similar behavior.

The message will appear in the On Screen Display and says
`RetroAchievements: logged in as "username".`

No need to merge. It's just to let you see the diff and say if you agree with the way I implemented it.

### CODE REVIEW

**Comment by meleu** [comment]
About the second commit:
The login error can happen for several reasons. So the message "Please make sure your account information is correct." is a bit excessive. I think "Retro Achievements login error." is enough.

**Comment by leiradel** [comment]
In the first commit, the brace should be right below the `if`. I also always do

```C++
msg[sizeof(msg) - 1] = 0;
```

because I don't trust `snprintf` terminating the string with a null character when the message doesn't fit in the buffer.

I think both commits are cool, have you sent a PR for the second commit? You should send one for the first too, I'm in the middle of porting [LÖVE](https://love2d.org/) to libretro and won't be looking for RetroArch for some time.

**Comment by meleu** [comment]
I did. :-)
https://github.com/libretro/RetroArch/pull/4217

Cheers!

**Comment by meleu** [comment]
this is already being discussed on libretro/RetroArch issue tracker. Closing here.

**Pull request closed without merging**
